### ISSUE TITLE
lidar2lidar auto_calib用自己的数据集报错

### ISSUE THREAD

**Issue by Sunnysunnyni** [PJLab-ADG/SensorsCalibration#111]
用速腾和禾赛的pcd都会报错
[pcl::PCDReader::read] Could not find file ''.
[ERROR] cannot open pcd_file: 
请问怎么解决呀？

**Comment by Sunnysunnyni** [comment]
已解决

**Comment by jiangroubao** [comment]
> 已解决

请问如何解决的呀
