### ISSUE TITLE
radar to camera make error

### ISSUE THREAD

**Issue by cumtbjt** [PJLab-ADG/SensorsCalibration#140]
Building CXX object CMakeFiles/RadarToCamera.dir/src/run_radar2camera.cpp.o
In file included from /home/lzl/PycharmProjects/calibration_ws/SensorsCalibration/radar2camera/manual_calib/src/run_radar2camera.cpp:23:
/home/lzl/PycharmProjects/calibration_ws/SensorsCalibration/radar2camera/manual_calib/include/extrinsic_param.hpp:11:10: fatal error: json/json.h: 没有那个文件或目录
   11 | #include <json/json.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/RadarToCamera.dir/build.make:63：CMakeFiles/RadarToCamera.dir/src/run_radar2camera.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:105：CMakeFiles/RadarToCamera.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by qszgit** [comment]
How did you solve it?
