### ISSUE TITLE
【factory_calib】question about pnp_solver

### ISSUE THREAD

**Issue by liang0724s** [PJLab-ADG/SensorsCalibration#25]
Hi, 
  Thanks for your great job. 
  There are three cost functions  definition(XCostFunctorPnP, YCostFunctorPnP, ZCostFunctorPnP), and for   extrinsic computing, you uesd the third one. What were the application conditions for them?

**Comment by xiaokn** [comment]
> Hi, Thanks for your great job. There are three cost functions definition(XCostFunctorPnP, YCostFunctorPnP, ZCostFunctorPnP), and for extrinsic computing, you uesd the third one. What were the application conditions for them?

The specific details can be seen in the code mainly to see the effect of the test.
