### ISSUE TITLE
imu数据的生成过程

### ISSUE THREAD

**Issue by lhlawrence** [PJLab-ADG/SensorsCalibration#26]
你好，我想请问一下top_center_lidar-utm 和top_center_lidar-enu还有top_center_lidar-pose之间是怎么操作的呢？最后生成的imu位姿都是相对于第一帧的吗？还是相对于上一帧？感谢

**Comment by LamHoCN** [comment]
mark

**Comment by xiaokn** [comment]
top_center_lidar-utm 和top_center_lidar-enu分别是utm和enu坐标系下的位姿，top_center_lidar-pose是加上外参之后的雷达相对于某一个坐标系的位姿，可以是第一帧也可以是其他坐标系

**Comment by h1063135843** [comment]
> top_center_lidar-utm 和top_center_lidar-enu分别是utm和enu坐标系下的位姿，top_center_lidar-pose是加上外参之后的雷达相对于某一个坐标系的位姿，可以是第一帧也可以是其他坐标系

这个lidar在utm和enu坐标系下的位姿是怎么相互转化的呀
