### ISSUE TITLE
lidar2imu autocalib

### ISSUE THREAD

**Issue by ManChrys** [PJLab-ADG/SensorsCalibration#33]
Hello,

for lidar2imu autocalibration should i put it on a car? Can i do the process as a pedestrian indoor or outdoor? 

I have a livox mid 40 and a xsens mti g 710 gnss/ins and i made a handheld system and i need to calibrate them

Thanks in advance.

**Comment by xiaokn** [comment]
> 

Yes, it doesn't have to be in the car
