### ISSUE TITLE
lidar2imu diverge

### ISSUE THREAD

**Issue by linwk20** [PJLab-ADG/SensorsCalibration#35]
Hi, Thanks for your sharing!
I have used the lidar2imu tool, however, the result seems to diverge.

`Ceres Solver Report: Iterations: 15, Initial cost: 2.748471e+03, Final cost: 2.717503e+03, Termination: CONVERGENCE`
 
I have given it a proper initialization. What could be the possible other reason?

Thanks!

**Comment by xiaokn** [comment]
> Hi, Thanks for your sharing! I have used the lidar2imu tool, however, the result seems to diverge.
> 
> `Ceres Solver Report: Iterations: 15, Initial cost: 2.748471e+03, Final cost: 2.717503e+03, Termination: CONVERGENCE`
> 
> I have given it a proper initialization. What could be the possible other reason?
> 
> Thanks!

You can pull the latest code and try again. It is better to have more surface features in the calibration environment.

**Comment by linwk20** [comment]
Hi, Thanks for your quick reply, I will try running the latest code.
Besides, I wonder is there other built-in debug way? For example, can I visualize the diverging process or the surface feature's distribution? now I can only received feedback from terminal.

**Comment by pedestrain123** [comment]
@linwk20 您好，请问你用自己的数据auto calib标定lidar2imu标定成功了吗？我用自己的数据集标定效果不理想，可以交流一下吗？期待您的回复

**Comment by linwk20** [comment]
no, i use other tools

**Comment by pedestrain123** [comment]
@linwk20 请问您用的是什么工具，lidar align吗？还是什么其他工具？可以推荐一下吗？能否加你微信或者QQ交流一下，QQ2985782675,v:19516191665

**Comment by linwk20** [comment]
Actually, other people take care of the calibration for me, I am not sure what they use too. The result was not good as well. I will recommend you to use other open-sourced calibration tool. Or try this repo on more datasets, maybe some will work.

**Comment by pedestrain123** [comment]
> 实际上，其他人帮我做了校准，我不确定他们用什么。结果也不好。我建议你使用其他开源校准工具。或者在更多数据集上尝试这个 repo，也许有些会起作用。

谢谢
