### ISSUE TITLE
lidar2imu的auto_calib 关于displayVoxelMap()的疑问

### ISSUE THREAD

**Issue by XiaoYihh** [PJLab-ADG/SensorsCalibration#51]
您好，我在lidar2imu的auto版本中用了displayVoxelMap()，
使用的example数据，但是结果与readme中的point cloud feature map不一样，物体会大量重复出现。
想请问一下这种现象的原因
![voxelMap](https://user-images.githubusercontent.com/55802457/210530044-375ec474-1986-42ee-af3d-5db5a7ae97e1.png)

**Comment by jiahao68** [comment]
出现物体大量重复的现象应该是外参不准确，即你用不准确的外参生成了feature map。

**Comment by XiaoYihh** [comment]
@jiahao68 谢谢你，问题解决了
