### ISSUE TITLE
How to get the initial value of external parameters between radar and camera?

### ISSUE THREAD

**Issue by alfanrizaldy** [PJLab-ADG/SensorsCalibration#54]
https://github.com/PJLab-ADG/SensorsCalibration/issues/3
I've see the answer in above link but still no idea how to obtain that
Can you slightly detail answering this question?
Thanks

**Comment by xiaokn** [comment]
> #3 I've see the answer in above link but still no idea how to obtain that Can you slightly detail answering this question? Thanks

For example, the translation can be measured, and the rotation is roughly corresponding to the coordinate axis of the installed sensor.

**Comment by xiaokn** [comment]
> So, it is manually metered? I got the idea for the rotation, so i measure how the facing angle of the radar Then, how to measure the translation? I mean, with what it compared or referred?

For example, use a ruler to measure manually or give the design value according to the CAD drawing.

**Comment by alfanrizaldy** [comment]
![radar-ruler](https://user-images.githubusercontent.com/27501641/220891653-8a133345-9131-4b25-9a35-baf75dcc1ebc.jpg)
I've made simple illustration above, then i measure the between the radar and what?
