### ISSUE TITLE
joint_calib

### ISSUE THREAD

**Issue by fengguibinyn** [PJLab-ADG/SensorsCalibration#64]
标定板四个圆心坐标是相对于棋盘格左上角的相对位置吗，看代码给的默认位置和标定板对应不上

**Comment by xiaokn** [comment]
> 标定板四个圆心坐标是相对于棋盘格左上角的相对位置吗，看代码给的默认位置和标定板对应不上

测试的数据是仿真生成的，和默认的标定板尺寸有一点点偏差

**Comment by fengguibinyn** [comment]
感谢您的回复，标定板的图片方便提供下吗 感谢

**Comment by CXT-666** [comment]
请问有标定板的图片吗
