### ISSUE TITLE
请问是否有兴趣组建个群方便大家交流学习

### ISSUE THREAD

**Issue by wxz1996** [PJLab-ADG/SensorsCalibration#8]

**Comment by yikang-li** [comment]
感谢建议。我们这两天安排上！稍后会把二维码发出来

**Comment by yikang-li** [comment]
![51654840162_ pic](https://user-images.githubusercontent.com/10878664/172999170-6ef8ec0c-5afe-4944-acc7-e34ede4c1798.jpg)

The QR Code of the WeChat group is attached.

**Comment by 24werewolf** [comment]
可以拉一下进群吗？现在这个群二维码失效了。

**Comment by whuzs** [comment]
可以帮忙更新一下群二维码吗?谢谢

**Comment by zhh2005757** [comment]
同，可以拉一下进群嘛

**Comment by piedaochuan1234** [comment]
可以拉一下进群吗，谢谢

**Comment by AMzhanghan** [comment]
> 感谢建议。我们这两天安排上！稍后会把二维码发出来

能拉下我不 WeChat：AMzhanghan

**Comment by Azmat-Liu** [comment]
能拉一下我嘛，Weixin ID: Naliziwang

**Comment by pedestrain123** [comment]
> > 感谢建议。我们这两天安排上！稍后会把二维码发出来
> 
> 能拉下我不 WeChat：AMzhanghan

你好，请问可以提供一下bag包转换pcd和NovAtel-pose-lidar-time.txt的脚本程序吗？我这边转换之后得到gnss相对于初始时刻的位姿变换和当前时刻的pcd点云，以及输入初始外参，得到的结果和初始外参相差几十米，不知道因为什么
