### ISSUE TITLE
IMU标定代码细节咨询

### ISSUE THREAD

**Issue by WeiJunREN** [PJLab-ADG/SensorsCalibration#81]
*/imu_heading/auto_calib/src/imu_heading.cpp 524-529行：
  extrinsic_mat[1][0] = -cos(-yaw_offset_rad);
  extrinsic_mat[1][2] = -sin(-yaw_offset_rad);
  extrinsic_mat[2][0] = -sin(-yaw_offset_rad);
  extrinsic_mat[2][2] = cos(-yaw_offset_rad);
  extrinsic_mat[0][1] = 1;
1.这里为什么不用欧拉角转换公式将yaw直接转换为旋转矩阵，而是采用上述方式转换呢。
2.上述是straightcalibratesingle模式的，只对yaw做了处理，如果是free模式，采用上述转换方法又如何转换rpy角度为旋转矩阵

**Comment by xiaokn** [comment]
> */imu_heading/auto_calib/src/imu_heading.cpp 524-529行： extrinsic_mat[1][0] = -cos(-yaw_offset_rad); extrinsic_mat[1][2] = -sin(-yaw_offset_rad); extrinsic_mat[2][0] = -sin(-yaw_offset_rad); extrinsic_mat[2][2] = cos(-yaw_offset_rad); extrinsic_mat[0][1] = 1; 1.这里为什么不用欧拉角转换公式将yaw直接转换为旋转矩阵，而是采用上述方式转换呢。 2.上述是straightcalibratesingle模式的，只对yaw做了处理，如果是free模式，采用上述转换方法又如何转换rpy角度为旋转矩阵

得到角度就可以了，转化角度的代码不需要哈，没啥用
